CREATE TABLE IF NOT EXISTS giocatori (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    vittorie INT DEFAULT 0
) ENGINE=InnoDB;
